serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'rag-api'
        scrape_interval: 10s
        static_configs:
          - targets: ['rag-api:80']
        metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

  rules:
    - name: rag-alerts
      rules:
        - alert: HighErrorRate
          expr: rate(rag_errors_total[5m]) > 0.1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High error rate in RAG pipeline
            description: Error rate is above 10% in the last 5 minutes

        - alert: SlowQueries
          expr: histogram_quantile(0.95, rate(rag_query_processing_seconds_bucket[5m])) > 5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Slow query processing
            description: 95th percentile of query processing time is above 5 seconds
