serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'rag-api'
        scrape_interval: 10s
        static_configs:
          - targets: ['rag-api:8000']
        metrics_path: /metrics
        relabel_configs:
          - source_labels: [__address__]
            target_label: service
            replacement: rag-api

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

  rules:
    - name: rag-alerts
      rules:
        - alert: HighErrorRate
          expr: rate(rag_errors_total[5m]) / rate(rag_queries_total[5m]) > 0.1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High error rate in RAG pipeline
            description: Error rate is above 10% in the last 5 minutes

        - alert: SlowQueries
          expr: histogram_quantile(0.95, rate(rag_query_processing_seconds_bucket[5m])) > 5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Slow query processing
            description: 95th percentile of query processing time is above 5 seconds

        - alert: HighMemoryUsage
          expr: container_memory_usage_bytes{container="rag-api"} / container_spec_memory_limit_bytes{container="rag-api"} > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High memory usage
            description: Memory usage is above 80% of the limit

        - alert: HighCPUUsage
          expr: rate(container_cpu_usage_seconds_total{container="rag-api"}[5m]) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High CPU usage
            description: CPU usage is above 80% for 5 minutes
