apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: rag-system
  labels:
    app: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: rag-api
        image: localhost:32000/igenius-rag:latest
        ports:
        - containerPort: 8000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: GROQ_API_KEY
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: ENV
        - name: GROQ_MODEL
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: GROQ_MODEL
        - name: VECTORDB_PATH
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: VECTORDB_PATH
        - name: RAW_DATA_PATH
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: RAW_DATA_PATH
        - name: PROCESSED_DATA_PATH
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: PROCESSED_DATA_PATH
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: vector-store
          mountPath: /app/data
      volumes:
      - name: vector-store
        persistentVolumeClaim:
          claimName: vector-store-pvc
