apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rag-api-scaler
  labels:
    app: rag-api
spec:
  scaleTargetRef:
    name: rag-api
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 300
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: http_requests_total
        threshold: '10'
        query: sum(rate(http_requests_total{service="rag-api"}[2m]))
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: rag_query_processing_seconds
        threshold: '3'
        query: histogram_quantile(0.95, sum(rate(rag_query_processing_seconds_bucket{service="rag-api"}[2m])) by (le))
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
    - type: memory
      metadata:
        type: Utilization
        value: "70"
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 50
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 30
