apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-system
type: Opaque
stringData:
  # Environment
  ENV: "development"
  
  # Groq Configuration
  GROQ_API_KEY: "your-api-key-here"
  GROQ_MODEL: "llama3-70b-8192"
  
  # Vector Database Configuration
  VECTORDB_PATH: "/app/data/vectordb"
  
  # Data Paths
  RAW_DATA_PATH: "/app/data/raw"
  PROCESSED_DATA_PATH: "/app/data/processed"
  
  
  # Application Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  
  # Monitoring
  PROMETHEUS_TOKEN: "your-prometheus-token"
  GRAFANA_ADMIN_PASSWORD: "your-grafana-admin-password" 