apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-system
type: Opaque
stringData:
  # API Keys
  GROQ_API_KEY: "your-groq-api-key-here"
  
  # Other Service Credentials
  HUGGINGFACE_API_KEY: "your-huggingface-api-key-here"
  
  # Application Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  
  # Monitoring
  PROMETHEUS_TOKEN: "your-prometheus-token"
  GRAFANA_ADMIN_PASSWORD: "your-grafana-admin-password" 