apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: rag-system
spec:
  selector:
    app: rag-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
